"""novos intens corrigidos e alterados

Revision ID: 1cdf27cb3b9d
Revises: aee6232ffa13
Create Date: 2021-06-01 21:34:40.104954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdf27cb3b9d'
down_revision = 'aee6232ffa13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
