"""novos intens corrigidos e alterados

Revision ID: 21eea187ce12
Revises: 3be27eaea8cc
Create Date: 2021-06-01 21:21:44.321430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eea187ce12'
down_revision = '3be27eaea8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_empresa', 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagem', schema=None) as batch_op:
        batch_op.drop_constraint('fk_empresa', type_='foreignkey')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
