"""novos intens corrigidos e alterados

Revision ID: 2c7bd31f63b6
Revises: 441ce1242712
Create Date: 2021-06-07 19:12:10.744738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7bd31f63b6'
down_revision = '441ce1242712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagemsimples', schema=None) as batch_op:
        batch_op.drop_index('ix_passagemsimples_id')

    op.drop_table('passagemsimples')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passagemsimples',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('embarque', sa.VARCHAR(), nullable=True),
    sa.Column('desembarque', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passagemsimples', schema=None) as batch_op:
        batch_op.create_index('ix_passagemsimples_id', ['id'], unique=False)

    # ### end Alembic commands ###
