"""novos intens corrigidos e alterados

Revision ID: 2f471746daa6
Revises: 83efdb720bf5
Create Date: 2021-06-03 12:18:27.986801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f471746daa6'
down_revision = '83efdb720bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passagemsimples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embarque', sa.String(), nullable=True),
    sa.Column('desembarque', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passagemsimples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passagemsimples_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagemsimples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passagemsimples_id'))

    op.drop_table('passagemsimples')
    # ### end Alembic commands ###
