"""novos intens corrigidos e alterados

Revision ID: 3be27eaea8cc
Revises: 37b7bfcd1d7b
Create Date: 2021-06-01 21:17:07.839059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be27eaea8cc'
down_revision = '37b7bfcd1d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
