"""novos intens corrigidos e alterados

Revision ID: 441ce1242712
Revises: 94147e2706ae
Create Date: 2021-06-03 17:11:15.302702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441ce1242712'
down_revision = '94147e2706ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('de', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('para', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=True))
        batch_op.drop_column('cnpj')

    with op.batch_alter_table('passagemsimples', schema=None) as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagemsimples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('valor')
        batch_op.drop_column('para')
        batch_op.drop_column('de')

    # ### end Alembic commands ###
