"""novos intens corrigidos e alterados

Revision ID: 45003b5d3a09
Revises: 3b7ad60f6fb5
Create Date: 2021-06-01 21:05:33.045365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45003b5d3a09'
down_revision = '3b7ad60f6fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passagem_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_passagem', 'passagem', ['passagem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('fk_passagem', type_='foreignkey')
        batch_op.drop_column('passagem_id')

    # ### end Alembic commands ###
