"""novos intens corrigidos e alterados

Revision ID: 487f24973038
Revises: f3437ff627d0
Create Date: 2021-06-08 19:07:10.905178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487f24973038'
down_revision = 'f3437ff627d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
