"""novos intens corrigidos e alterados

Revision ID: 5d13a429b0df
Revises: 21eea187ce12
Create Date: 2021-06-01 21:26:07.479644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d13a429b0df'
down_revision = '21eea187ce12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
