"""novos intens corrigidos e alterados

Revision ID: 83efdb720bf5
Revises: 1cdf27cb3b9d
Create Date: 2021-06-03 11:26:35.016321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83efdb720bf5'
down_revision = '1cdf27cb3b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
