"""novos intens corrigidos e alterados

Revision ID: 94147e2706ae
Revises: 2f471746daa6
Create Date: 2021-06-03 16:45:43.893366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94147e2706ae'
down_revision = '2f471746daa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
