"""novos intens corrigidos e alterados

Revision ID: aee6232ffa13
Revises: 5d13a429b0df
Create Date: 2021-06-01 21:28:08.126951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee6232ffa13'
down_revision = '5d13a429b0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagem', schema=None) as batch_op:
        batch_op.drop_constraint('fk_empresa', type_='foreignkey')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_empresa', 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###
