"""nova revisao

Revision ID: e56878197b56
Revises: 2fc6b5d31ca4
Create Date: 2021-05-25 20:03:25.460554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56878197b56'
down_revision = '2fc6b5d31ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
