"""novos intens corrigidos e alterados

Revision ID: f3437ff627d0
Revises: 2c7bd31f63b6
Create Date: 2021-06-07 20:16:25.550763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3437ff627d0'
down_revision = '2c7bd31f63b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
